backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;


# Fading settings
fading = true;               # Enable fading for windows
fade-delta = 7;             # Fading speed;
fade-in-step = 0.03;         # Fade-in step
fade-out-step = 0.03;        # Fade-out step
no-fading-openclose = false; # Fade windows on open/close

