# Font
font_family Hack Nerd Font Mono 
italic_font Hack Nerd Font Mono Regular
bold_italic_font Hack Nerd Font Mono Bold

font_size 17.0

term xterm-256color
background_opacity 0.80

enable_audio_bell no

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

