set -g default-terminal "tmux-256color"

unbind %
bind h split-window -h

unbind '"'
bind v split-window -v

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'jimeh/tmux-themepack' # to configure tmux theme

# set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @themepack 'powerline/default/blue' # use this theme for tmux
# set -g @plugin 'fabioluciano/tmux-tokyo-night'

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
