backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;
fading = true;

fade-in-step = 1.0;
fade-out-step = 1.0;
fade-delta = 1;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;
