require("surajb.plugins-setup")
require("surajb.core.options")
require("surajb.core.keymaps")
-- require("surajb.core.colorscheme")
require("surajb.plugins.neosolarized")
require("surajb.plugins.comment")
require("surajb.plugins.nvim-tree")
require("surajb.plugins.lualine")
require("surajb.plugins.telescope")
require("surajb.plugins.nvim-cmp")
require("surajb.plugins.lsp.mason")
-- require("surajb.plugins.lsp.lspsaga")
require("surajb.plugins.lsp.lspconfig")
require("surajb.plugins.lsp.null-ls")
require("surajb.plugins.autopairs")
require("surajb.plugins.treesitter")
