#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspwmrc - settings section

bspc monitor -d I II III IV V VI VII VIII IX X
# Appearance
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

# Colors
# bspc config normal_border_color   '#32344a'
# bspc config active_border_color   '#444b6a'
# bspc config focused_border_color  '#7aa2f7'
# bspc config presel_feedback_color '#9ece6a'

# Behavior
bspc config split_ratio           0.52
bspc config automatic_scheme      longest_side
bspc config removal_adjustment    true

# Focus
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config click_to_focus        button1
bspc config swallow_first_click   false

# Pointer
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

# Monocle
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   false
bspc config single_monocle        false

bspc rule -a vicinae border=off

# Monitors
# bspc config remove_disabled_monitors  true
# bspc config remove_unplugged_monitors true
# bspc config merge_overlapping_monitors true

picom &
feh --bg-scale ~/Pictures/wallhaven-5yrwq8.jpg
xsetroot -cursor_name left_ptr
sxhkd &
lxpolkit &
vicinae server &
nm-applet &
dunst &
bash ~/.config/polybar/launch.sh  &
