color0 #42474e
color1 #ffb4ab
color2 #9bcbfc
color3 #b7c8de
color4 #e8b5f1
color5 #9bcbfc
color6 #b7c8de
color7 #e2e2e6
color8 #8c9199
color9 #ffb4ab
color10 #9bcbfc
color11 #b7c8de
color12 #e8b5f1
color13 #9bcbfc
color14 #b7c8de
color15 #e2e2e6

cursor                #e2e2e6
cursor_text_color     #111416
background            #111416
foreground            #e2e2e6
selection_foreground  #c2c7d0
selection_background  #42474e
active_border_color   #9bcbfc
inactive_border_color #42474e
url_color             #9bcbfc

active_tab_foreground   #003354
active_tab_background   #9bcbfc
inactive_tab_foreground #c2c7d0
inactive_tab_background #42474e
cursor_trail_color      #c2c7d0
