# Fonts
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        18.0

# Window Layout & Padding
# window_padding_width 10
hide_window_decorations no
background_opacity 0.85

# Cursor
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0.5

# ouse & URLs
url_color #0087bd
url_style curly
detect_urls yes

# Advanced / Quality of Life
confirm_os_window_close 0
enable_audio_bell no
